# Generated by Django 3.1.1 on 2020-09-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthFBUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('userid', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='userid')),
                ('name', models.CharField(max_length=50, verbose_name='fb帳號用戶名稱')),
                ('photo_url', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='用戶照片')),
            ],
            options={
                'verbose_name': 'fb用戶',
                'verbose_name_plural': 'fb用戶',
                'db_table': 'tb_fb_user',
            },
        ),
        migrations.CreateModel(
            name='OAuthGoogleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('userid', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='userid')),
                ('name', models.CharField(max_length=50, verbose_name='google帳號用戶名稱')),
                ('photo_url', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='用戶照片')),
            ],
            options={
                'verbose_name': 'google用戶',
                'verbose_name_plural': 'google用戶',
                'db_table': 'tb_google_user',
            },
        ),
        migrations.CreateModel(
            name='OAuthLineUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('userid', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='userid')),
                ('name', models.CharField(max_length=50, verbose_name='line帳號用戶名稱')),
                ('photo_url', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='用戶照片')),
            ],
            options={
                'verbose_name': 'line用戶',
                'verbose_name_plural': 'line用戶',
                'db_table': 'tb_line_user',
            },
        ),
    ]
