# Generated by Django 3.1.1 on 2020-09-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo圖片'),
        ),
    ]
