# Generated by Django 3.1.1 on 2020-09-23 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0004_goodsvisitcount'),
        ('users', '0003_auto_20200912_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='訂單號碼')),
                ('total_count', models.IntegerField(default=1, verbose_name='商品總數')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品總金額')),
                ('freight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='運費')),
                ('pay_method', models.SmallIntegerField(choices=[(1, '貨到付款'), (2, '支付寶'), (3, 'LinePay')], default=1, verbose_name='支付方式')),
                ('status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '待發貨'), (3, '待收貨'), (4, '待評價'), (5, '已完成'), (6, '已取消')], default=1, verbose_name='訂單狀態')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.address', verbose_name='收貨地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='下單用戶')),
            ],
            options={
                'verbose_name': '訂單基本資料',
                'verbose_name_plural': '訂單基本資料',
                'db_table': 'tb_order_info',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('count', models.IntegerField(default=1, verbose_name='數量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('comment', models.TextField(default='', verbose_name='評價資訊')),
                ('score', models.SmallIntegerField(choices=[(0, '0顆星'), (1, '1顆星'), (2, '2顆星'), (3, '3顆星'), (4, '4顆星'), (5, '5顆星')], default=5, verbose_name='滿意度評分')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名評價')),
                ('is_commented', models.BooleanField(default=False, verbose_name='是否評價')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='orders.orderinfo', verbose_name='訂單')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.sku', verbose_name='訂單商品')),
            ],
            options={
                'verbose_name': '訂單商品',
                'verbose_name_plural': '訂單商品',
                'db_table': 'tb_order_goods',
            },
        ),
    ]
